export { Nav } from "./Nav";
export { Hero } from "./Hero";
export { SocialStrip } from "./SocialStrip";
export { Statement } from "./Statement";
export { Pillars } from "./Pillars";
export { Press } from "./Press";
export { Motion } from "./Motion";
export { Gallery } from "./Gallery";
export { Product } from "./Product";
export { Declare } from "./Declare";
export { Footer } from "./Footer";
export { PageHead } from "./PageHead";
export { LegalPage, type LegalSection } from "./LegalPage";
